:default_deltacloud_url: http://localhost:3002/api

:auth:
  # supported strategies: database, ldap
  :strategy: database
:groups:
  # allows locally-managed groups
  :enable_local: true
  # allows ldap-managed groups
  :enable_ldap: true

:imagefactory:
  :url: https://localhost:8075/imagefactory
  :callback_urls:
    :target_image: http://admin:password@<%= conductor_hostname %>:<%= conductor_port %>/tim/target_images
    :provider_image: http://admin:password@<%= conductor_hostname %>:<%= conductor_port %>/tim/provider_images
  :oauth:
    :consumer_key: <%= imagefactory_oauth_user %>
    :consumer_secret: <%= imagefactory_oauth_password %>

:session:
  :timeout: 480 # minutes

:action_mailer:
  :delivery_method: sendmail # or smtp
  # use this configuration if you use smtp as delivery_method
  # :smtp_settings:
  # :address: smtp.gmail.com
  # :port: 587
  # :domain: example.aeolusproject.org
  # :user_name: <username>,
  # :password: <password>
  # :authentication: plain
  # :enable_starttls_auto: true
  :default_url_options:
    :host: localhost/conductor
    :protocol: https
  :default_from: admin@example.com
  :password_reset_token_timeout: 120 #minutes
